version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud-cost-tracker
    volumes:
      - .:/app
      - go-cache:/go/pkg/mod
      - tmp-data:/app/tmp
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://user:pass@postgres:5432/cloud_cost_tracker?sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: cloud-cost-tracker-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cloud_cost_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cloud-cost-tracker-redis
    ports:
      - "6379:6379"

  migrate:
    image: migrate/migrate
    command: ["-path", "/migrations", "-database", "postgres://user:pass@postgres:5432/cloud_cost_tracker?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres

volumes:
  pgdata:
  go-cache:
  tmp-data:
