server:
  port: 8080

db:
  dsn: "postgres://user:pass@localhost:5432/cloud_cost_tracker?sslmode=disable"
  maxOpenConns: 25
  maxIdleConns: 5

redis:
  addr: "127.0.0.1:6379"
  db: 0

auth:
  jwtSecret: "change-me"
  tokenTTL: "24h"

providers:
  gcp:
    billingProjectID: "your-billing-project"
    dataset: "billing_export"
  aws:
    enabled: false
  alibaba:
    enabled: false
