server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: cloud_cost_tracker
  sslmode: disable

auth:
  jwt_secret: "supersecretjwtkey"

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "https://yourdomain.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Content-Length"
    - "Accept-Encoding"
    - "X-CSRF-Token"
    - "Authorization"
    - "accept"
    - "origin"
    - "Cache-Control"
    - "X-Requested-With"
    - "AuthToken"
    - "access-token"
    - "x-app-key"
    - "X-Authorization"
    - "Referer"
    - "Keep-Alive"
    - "User-Agent"
    - "If-Modified-Since"
    - "LoginProvider"
    - "X-Jwt-Token"
  allow_credentials: true

cloud:
  gcp:
    project_id: "my-gcp-project"
    billing_dataset: "billing_export"
  aws:
    account_id: "123456789012"
    region: "us-east-1"
  alibaba:
    account_id: "alibaba-account-id"
    region: "ap-southeast-1"
